# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'BaekJoonProfile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaekJoonProfile
 pod 'SDWebImageSwiftUI'
 pod 'SDWebImageSVGCoder'
 pod 'Alamofire'
 pod 'BottomSheet', :git => 'https://github.com/weitieda/bottom-sheet.git'
 target 'ProfileWidgetExtension' do
 pod 'Alamofire'
 pod 'SDWebImageSwiftUI'
 end
end
